openapi: "3.0.1"
info:
  title: "Rekognition"
  version: "1.0.0"

x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: false
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

paths:
  /detectface:
    post:

      responses:
        "200":
          description: "200"

      ## API Gateway Integration
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiRole, Arn]
        type: "aws"
        httpMethod: "POST"
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FaceDetectionFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        #payloadFormatVersion: "1.0"

        responses:
          "":
            statusCode: "200"
            responseTemplates:
              application/json: ""

